#version 460
#extension GL_EXT_buffer_reference : require

layout(local_size_x = 4, local_size_y = 2, local_size_z = 2) in;
layout(buffer_reference, std430, buffer_reference_align = 4) buffer Data {
    uint values[];
};
layout(push_constant, std430) uniform Root {
    Data data;
    uint width;
    uint height;
    uint depth;
} root;

uint encode(uvec3 v) { return 1u + v.x + 100u * v.y + 10000u * v.z; }

void main() {
    uvec3 p = gl_GlobalInvocationID;
    if (any(greaterThanEqual(p, uvec3(root.width, root.height, root.depth)))) return;
    uint i = 4u * ((p.z * root.height + p.y) * root.width + p.x);
    // Addition detects duplicate invocations/dispatches as well as missing ones.
    root.data.values[i + 0] += encode(p);
    root.data.values[i + 1] += encode(gl_WorkGroupID);
    root.data.values[i + 2] += encode(gl_LocalInvocationID);
    root.data.values[i + 3] += encode(gl_NumWorkGroups);
}
